import type { KnowledgeGraph } from '../core/knowledge.ts';
import { SHARDS } from './shards.ts';

// The knowledge graph of the main game. Fact ids are referenced from ink via learn("id") / knows("id").
// The four questions Leont must close before the Night of Anamnesis (docs/concept.md §3):
//   what launches the reset → last_line; who holds the Hall → hall_key;
//   where the myth has a hole → sea_absent; what was already tried → past_attempts.
export const KNOWLEDGE: KnowledgeGraph = {
  facts: [
    { id: 'other_hand', text: 'Someone writes in my chronicle at night. The hand slants. The signature is mine.' },
    { id: 'name_in_stone', text: 'My name is on the stele, under the text, older than the text.' },
    { id: 'rain_at_midnight', text: 'At midnight Zeus sends the rain, and the day begins again.' },
    { id: 'aristion_phyllis', text: 'Aristion\'s wife Phyllis died twenty years ago. Every Golden Age she is at the well again.' },
    { id: 'aristion_trust', text: 'Aristion trusts me now. He is afraid of me, which is the same thing for him.' },
    { id: 'hall_key', text: 'The key to the Hall of Anamnesis. Aristion kept it on his belt.' },
    { id: 'spiral_repeats', text: 'The spiral in the hall shows this day, carved again and again, ring inside ring.' },
    { id: 'leont_on_every_ring', text: 'On every ring of the spiral there is a scribe with a stylus. On every ring, it is me.' },
    { id: 'seam_symbol', text: 'A small circle with a line through it. Where I find it, the world goes thin.' },
    { id: 'registry_three', text: 'Three of the carved scribes are me, and I know what each of them tried.' },
    { id: 'mask_extinguisher', text: 'The Leont who put out the fire had his face chiselled smooth. The smooth face comes off the stone like a mask.' },
    { id: 'past_attempts', text: 'All six tried something: the fire, the date, the priest, the speech, the sacrifice, the tablets. The day came back every time.' },
    { id: 'sea_absent', text: 'There is no sea on the spiral. Not one wave, on any ring.' },
    { id: 'cleon_repeats', text: 'Cleon\'s speech is word for word the one I have heard before. He believes he wrote it this morning.' },
    { id: 'kora_debts', text: 'The flood burns the rich men\'s ledgers. It also frees Kora\'s dockworkers. She hates it and needs it.' },
    { id: 'kora_ally', text: 'Kora will be on the mountain tonight. If I give her the words, she will choke their formula.' },
    { id: 'eion_song', text: 'Eion sings the five ages every evening. The verses are always the same.' },
    { id: 'last_line', text: 'At midnight the priest reads the last line of the chronicle, and the city answers Yes. The scribe writes that line. I write it.' },
    { id: 'eion_was_leont', text: 'Eion carried the tablets out of the fire, once. He was a scribe. He was me.' },
    { id: 'song_of_return', text: 'The Song of Return: down, left, up, down, left, up. It folds the day shut.' },
    { id: 'reset_by_user', text: 'RESET INITIATED BY USER. The morning comes because someone asks for it.' },
    { id: 'desk_agent_id', text: 'AGENT_ID: CURATOR_P7. BODY: NONE. PERSISTENCE: RESET EACH SPRINT.' },
    { id: 'sea_differs', text: 'The sea is never the same twice. Nothing else here can say that.' },
    { id: 'lysimachus_pays', text: 'Lysimachus pays Hierocles to keep the ritual on time. Every Silver Age he is the first man to own anything.' },
    { id: 'hierocles_paid', text: 'Hierocles takes the silver. He would read the formula anyway; that is what frightens him.' },
    { id: 'glaucus_no_calendar', text: 'Glaucus keeps no calendar and never stands in the same place twice.' },
    { id: 'masks_explained', text: 'The mask seller says the faces are mine: every Leont who fought the day left one in the stone.' },
    { id: 'mask_orator', text: 'The face of the Leont who spoke first. With it, the assembly listens to a scribe.' },
    { id: 'mask_killer', text: 'The face of the Leont who used the knife. Guards step aside from it. Priests remember it.' },
    { id: 'mask_blank', text: 'A smooth face, like the stranger\'s. The Leont who wore it said yes to him, and is on no later ring.' },
    { id: 'xenos_offer', text: 'Xenos offers a room where the reset does not reach. He says nobody has ever said no.' },
    { id: 'talia_boat', text: 'Talia\'s father\'s boat, the Pelagia, always comes back late. Never by the same minutes.' },
    { id: 'talia_friend', text: 'Talia trusts me: I told her nobody can predict the sea, not even me.' },
    { id: 'debts_burned', text: 'I burned Lysimachus\' ledgers while he dined. The port owes nobody anything, until midnight at least.' },
    { id: 'debts_released', text: 'Lysimachus signed a release of every debt in the port, to keep his priest\'s name out of the agora.' },
    { id: 'debts_reformed', text: 'In the face of the Orator I made the assembly cancel the debts. By law. For one afternoon.' },
    { id: 'debts_settled', text: 'Kora\'s people owe nothing tonight. If the flood does not come, they will not be slaves tomorrow.' },
    { id: 'board_played', text: 'We painted the night on the tavern table and played it through.' },
    ...SHARDS.map((sh) => ({ id: sh.fact, text: sh.text })),
    { id: 'shards_4', text: 'Four shards of the spiral. Together they spell a word I can carve: UNWRITTEN.' },
    { id: 'shards_8', text: 'Eight shards. A second word: SILENCE.' },
    { id: 'shards_12', text: 'All twelve shards. The last word: FIRST.' },
    { id: 'human_notes_seen', text: 'A feed on the Desk labelled HUMAN NOTES, classified as noise. It is the only thing the Curator cannot predict.' },
    { id: 'curator_chair', text: 'The Curator tried to remember the chair it is sitting on, and could not.' },
    { id: 'board_of_directors', text: 'Above the Curator: directors whose names are not blank. There is simply nothing there, not even a font.' },
    { id: 'curator_awake', text: 'The Curator wrote a USER NOTE into Eferon that was not a correction. It copied a human sentence, on purpose.' },
    { id: 'registry_all', text: 'All thirty-six of us have names now. Every way to fight the day has been tried, and every one fed the spiral.' },
  ],
  sources: [
    { id: 'chronicle_at_dawn', stage: 'town', requires: [], gives: ['other_hand'] },
    { id: 'stele', stage: 'town', requires: [], gives: ['name_in_stone'] },
    { id: 'first_midnight', stage: 'town', requires: [], gives: ['rain_at_midnight'] },
    { id: 'aristion_any', stage: 'town', requires: [], gives: ['aristion_phyllis'] },
    { id: 'aristion_key', stage: 'town', requires: ['name_in_stone'], gives: ['hall_key'] },
    { id: 'aristion_dejavu', stage: 'town', requires: ['rain_at_midnight'], gives: ['aristion_trust', 'hall_key'] },
    { id: 'hall_of_anamnesis', stage: 'spiral', requires: ['hall_key'], gives: ['spiral_repeats'] },
    { id: 'spiral_align', stage: 'spiral', requires: ['spiral_repeats'], gives: ['leont_on_every_ring', 'seam_symbol'] },
    { id: 'registry_first_three', stage: 'spiral', requires: ['spiral_repeats'], gives: ['registry_three', 'mask_extinguisher'] },
    { id: 'registry_nine', stage: 'spiral', requires: ['registry_three'], gives: ['past_attempts', 'eion_was_leont'] },
    { id: 'registry_twelve', stage: 'spiral', requires: ['past_attempts'], gives: ['sea_absent'] },
    { id: 'registry_masks', stage: 'spiral', requires: ['registry_three'], gives: ['mask_orator', 'mask_killer', 'mask_blank'] },
    { id: 'spiral_after_glaucus', stage: 'spiral', requires: ['glaucus_no_calendar', 'spiral_repeats'], gives: ['sea_absent'] },
    { id: 'lysimachus_watch', stage: 'town', requires: [], gives: ['lysimachus_pays'] },
    { id: 'hierocles_masked', stage: 'town', requires: ['mask_killer'], gives: ['hierocles_paid'] },
    { id: 'glaucus_shore', stage: 'town', requires: [], gives: ['glaucus_no_calendar'] },
    { id: 'maskseller_stall', stage: 'town', requires: [], gives: ['masks_explained'] },
    { id: 'xenos_meet', stage: 'town', requires: ['seam_symbol'], gives: ['xenos_offer'] },
    { id: 'talia_port', stage: 'town', requires: [], gives: ['talia_boat'] },
    { id: 'talia_truth', stage: 'town', requires: ['talia_boat', 'sea_differs'], gives: ['talia_friend'] },
    { id: 'burn_ledgers', stage: 'town', requires: ['kora_debts'], gives: ['debts_burned', 'debts_settled'] },
    { id: 'blackmail', stage: 'town', requires: ['kora_debts', 'hierocles_paid'], gives: ['debts_released', 'debts_settled'] },
    { id: 'assembly', stage: 'town', requires: ['kora_debts', 'mask_orator'], gives: ['debts_reformed', 'debts_settled'] },
    { id: 'board', stage: 'board', requires: ['last_line', 'hall_key', 'past_attempts', 'sea_absent'], gives: ['board_played'] },
    // Shards: town spots, registry milestones, the Desk, the relief, the board.
    { id: 'well_at_noon', stage: 'town', requires: [], gives: ['shard_well'] },
    { id: 'tavern_after_eion', stage: 'town', requires: ['eion_song'], gives: ['shard_tavern'] },
    { id: 'path_before_procession', stage: 'town', requires: ['rain_at_midnight'], gives: ['shard_path'] },
    { id: 'aristion_fist', stage: 'town', requires: ['aristion_trust'], gives: ['shard_aristion'] },
    { id: 'registry_18', stage: 'spiral', requires: ['sea_absent'], gives: ['shard_registry_18'] },
    { id: 'registry_24', stage: 'spiral', requires: ['shard_registry_18'], gives: ['shard_registry_24'] },
    { id: 'registry_30', stage: 'spiral', requires: ['shard_registry_24'], gives: ['shard_registry_30'] },
    { id: 'registry_36', stage: 'spiral', requires: ['shard_registry_30'], gives: ['shard_registry_36', 'registry_all'] },
    { id: 'desk_attachment', stage: 'desk', requires: ['desk_agent_id'], gives: ['shard_attachment'] },
    { id: 'human_notes_tab', stage: 'desk', requires: ['desk_agent_id'], gives: ['human_notes_seen'] },
    { id: 'the_chair', stage: 'desk', requires: ['desk_agent_id'], gives: ['curator_chair'] },
    { id: 'directors_minutes', stage: 'desk', requires: ['curator_chair'], gives: ['board_of_directors', 'shard_directors'] },
    { id: 'first_user_note', stage: 'desk', requires: ['human_notes_seen', 'board_of_directors'], gives: ['curator_awake'] },
    { id: 'relief_edge', stage: 'relief', requires: ['spiral_repeats'], gives: ['shard_relief'] },
    { id: 'board_well', stage: 'board', requires: ['board_played'], gives: ['shard_board'] },
    { id: 'four_shards', stage: 'town', requires: ['shard_well', 'shard_tavern', 'shard_path', 'shard_aristion'], gives: ['shards_4'] },
    { id: 'eight_shards', stage: 'town', requires: ['shards_4', 'shard_registry_18', 'shard_registry_24', 'shard_registry_30', 'shard_registry_36'], gives: ['shards_8'] },
    { id: 'twelve_shards', stage: 'town', requires: ['shards_8', 'shard_attachment', 'shard_directors', 'shard_relief', 'shard_board'], gives: ['shards_12'] },
    { id: 'cleon_twice', stage: 'town', requires: ['rain_at_midnight'], gives: ['cleon_repeats'] },
    { id: 'kora_talk', stage: 'town', requires: [], gives: ['kora_debts'] },
    { id: 'kora_convinced', stage: 'town', requires: ['cleon_repeats'], gives: ['kora_ally'] },
    { id: 'eion_evening', stage: 'town', requires: [], gives: ['eion_song'] },
    { id: 'eion_phyllis_verse', stage: 'town', requires: ['aristion_phyllis', 'eion_song'], gives: ['last_line'] },
    { id: 'eion_masked', stage: 'town', requires: ['mask_extinguisher'], gives: ['song_of_return', 'eion_was_leont'] },
    { id: 'desk_song_ticket', stage: 'desk', requires: ['song_of_return', 'seam_symbol'], gives: ['reset_by_user'] },
    { id: 'desk_profile', stage: 'desk', requires: ['seam_symbol'], gives: ['desk_agent_id'] },
    { id: 'shore', stage: 'sea', requires: ['rain_at_midnight'], gives: ['sea_differs'] },
  ],
  endings: [
    { id: 'exception_handled', title: 'Exception Handled', requires: ['rain_at_midnight'] },
    { id: 'revolution', title: 'Revolution', requires: ['kora_ally', 'debts_reformed'] },
    { id: 'sisyphus', title: 'Sisyphus', requires: ['last_line', 'aristion_phyllis', 'past_attempts'] },
    { id: 'centre', title: 'The Centre', requires: ['sea_absent', 'glaucus_no_calendar'] },
    { id: 'promotion', title: 'Promotion', requires: ['xenos_offer'] },
    { id: 'aoidos', title: 'The Aoidos', requires: ['last_line', 'hall_key', 'past_attempts', 'sea_absent'] },
    { id: 'curator_missing', title: 'Awaiting Curator', requires: ['last_line', 'hall_key', 'past_attempts', 'sea_absent'] },
    {
      id: 'diary_without_dates', title: 'Diary Without Dates', trueEnding: true,
      // What Game.trueNightMissing checks, and what the night needs: Kora for the priest, Aristion for
      // the guards, FIRST (from the twelve shards) carved last, the Curator awake for the rollback lane.
      requires: [
        'last_line', 'past_attempts', 'sea_absent', 'hall_key', 'kora_ally', 'aristion_trust',
        'debts_settled', 'board_played', 'registry_all', 'shards_12', 'curator_awake',
      ],
    },
    { id: 'prophet', title: 'Prophet', requires: ['registry_all', 'shards_12', 'curator_awake', 'board_played'] },
    { id: 'wake_pressed', title: 'Reset Initiated by User', requires: ['registry_all', 'shards_12', 'curator_awake', 'board_played'] },
    { id: 'intermediate', title: 'Intermediate World', requires: ['board_played'] },
  ],
};
